---

- hosts: localhost
  gather_facts: false

  vars:
    DDVE_public_IP: 3.126.240.82
    destination_port: 3009
    Instance_id: 'i-0df218424de9442a1'
    access_token: '651ea7afc1b0ad51bc8010a25265a721f'
    new_passphrase: 'Passsword123!'
    S3_bucket_name: 'ddve6-bucket-terraform'

  tasks:
   
    - name: create filesystem
      uri:
        validate_certs: false
        status_code: 200
        url: https://{{ DDVE_public_IP }}:{{ destination_port }}/{{ resource_path_1 }}
        method: PUT
        body_format: json
        body: 
          { "operation": "create" }
        headers:
            X-DD-AUTH-TOKEN: "{{ access_token }}"
            Content-Type: 'application/json'
        return_content: true
      register: rest_response
      vars:
        resource_path_1: rest/v1.0/dd-systems/0/file-systems

    - name: DEBUG update license / GOT INFO
      debug:
        msg: "{{ rest_response.json }}"
      when: rest_response.status ==  200