---

- hosts: localhost
  gather_facts: false

  vars:
    DDVE_public_IP: 34.107.103.175
    destination_port: 3009
    Instance_id: 'Password1234!'
    access_token: 'def681a832a93b1a431d39e8e39561025'

  tasks:
   
    - name: change from default login with new password
      uri:
        validate_certs: false
        status_code: 200
        url: https://{{ DDVE_public_IP }}:{{ destination_port }}/{{ resource_path_1 }}
        method: PUT
        body_format: json
        body: 
          new_password: 'Password0815!'
          current_password: "{{ Instance_id | string }}"
        headers:
            X-DD-AUTH-TOKEN: "{{ access_token }}"
            Content-Type: 'application/json'
        return_content: true
      register: rest_response
      vars:
        resource_path_1: rest/v1.0/dd-systems/0/users/sysadmin

    - name: DEBUG DD default password change / GOT INFO
      debug:
        msg: "{{ rest_response }}"
      when: rest_response.status ==  200