---

- hosts: localhost
  gather_facts: false

  vars:
    DDVE_public_IP: 3.126.240.82
    destination_port: 3009
    Instance_id: 'i-0df218424de9442a1'
    access_token: '651ea7afc1b0ad51bc8010a25265a721f'
    new_passphrase: 'Passsword123!'

  tasks:
   
    - name: change passphrase after install
      uri:
        validate_certs: false
        status_code: 200
        url: https://{{ DDVE_public_IP }}:{{ destination_port }}/{{ resource_path_1 }}
        method: PUT
        body_format: json
        body: 
          { "operation":"set_pphrase","pphrase_request":{ "new_pphrase":"{{ new_passphrase }}" }}
        headers:
            X-DD-AUTH-TOKEN: "{{ access_token }}"
            Content-Type: 'application/json'
        return_content: true
      register: rest_response
      vars:
        resource_path_1: rest/v3.0/dd-systems/0/systems

    - name: DEBUG DD change passphrase / GOT INFO
      debug:
        msg: "{{ rest_response }}"
      when: rest_response.status ==  200