---

- hosts: localhost
  gather_facts: false

  vars:
    DDVE_public_IP: 34.107.103.175
    destination_port: 3009
    access_token: 'def681a832a93b1a431d39e8e39561025'
    S3_bucket_name: bucket_for_ddve_6

  tasks:
   
    - name: enable object storage on Amazon aws
      uri:
        validate_certs: false
        status_code: 200
        url: https://{{ DDVE_public_IP }}:{{ destination_port }}/{{ resource_path_1 }}
        method: PUT
        body_format: json
        body: {"bucketType": "{{ S3_bucket_name }","acceptCertificate": true, "disks": ["dev3"]}
        headers:
            X-DD-AUTH-TOKEN: "{{ access_token }}"
            Content-Type: 'application/json'
        return_content: true
      register: rest_response
      vars:
        resource_path_1: api/v1/dd-systems/0/file-systems/object-stores/aws

    - name: DEBUG enable object store / GOT INFO
      debug:
        msg: "{{ rest_response.json }}"
      when: rest_response.status ==  200